# Generated by Django 5.2.11 on 2026-02-15 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Governor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo_url", models.URLField(blank=True)),
                ("party", models.CharField(blank=True, max_length=100)),
                ("votes_received", models.PositiveIntegerField(default=0)),
                ("manifesto_summary", models.TextField(blank=True)),
                (
                    "election_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governors",
                        to="core.electioncycle",
                    ),
                ),
            ],
            options={
                "ordering": ["election_cycle__start_year"],
                "unique_together": {("name", "election_cycle")},
            },
        ),
        migrations.CreateModel(
            name="GovernorPerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=200)),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("year", models.PositiveIntegerField()),
                (
                    "governor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="officials.governor",
                    ),
                ),
            ],
            options={
                "ordering": ["governor", "year", "metric_name"],
            },
        ),
        migrations.CreateModel(
            name="MemberOfParliament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo_url", models.URLField(blank=True)),
                ("party", models.CharField(blank=True, max_length=100)),
                ("votes_received", models.PositiveIntegerField(default=0)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "election_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mps",
                        to="core.electioncycle",
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mps",
                        to="core.subcounty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member of Parliament",
                "verbose_name_plural": "Members of Parliament",
                "ordering": ["sub_county__name", "election_cycle__start_year"],
                "unique_together": {("sub_county", "election_cycle")},
            },
        ),
        migrations.CreateModel(
            name="MPActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("constituency_visit", "Constituency Visit"),
                            ("wedding_attended", "Wedding Attended"),
                            ("parliament_session", "Parliament Session"),
                            ("fundraiser", "Fundraiser / Harambee"),
                            ("public_event", "Public Event"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("source_url", models.URLField(blank=True)),
                (
                    "mp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="officials.memberofparliament",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MP activities",
                "ordering": ["-date"],
            },
        ),
    ]
